branch-defaults:
  default:
    environment: checkout-env
environment-defaults:
  checkout-env:
    branch: null
    repository: null
global:
  application_name: CheckOut
  default_ec2_keyname: aws-eb
  default_platform: Python 3.9 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
