language: python

python:
  - "3.9"

install:
  - pip install -r requirements.txt
  - mkdir coverall
  - curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C ./coverall

before_script:
  - python manage.py makemigrations
  - python manage.py migrate

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_KEY"
  secret_access_key: "$AWS_SECRET"
  region: "$REGION"
  app: "$APP_NAME"
  env: "$ENV_NAME"
  bucket_name: "$BUCKET_NAME"
  on:
    branch: develop