language: python

python:
- "3.9"

install:
- pip install -r requirements.txt
- mkdir coverall
- curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C ./coverall

script:
- black --check .
- flake8 . --max-line-length=99
- coverage run manage.py test --noinput
- coverage xml
- ./coverall/coveralls report --repo-token=$COVERALL_TOKEN ./coverage.xml

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_KEY"
  secret_access_key: "$AWS_SECRET"
  region: "$REGION"
  app: "$APP_NAME"
  env: "$ENV_NAME"
  bucket_name: "$BUCKET_NAME"
  on:
    branch: develop
