# Generated by Django 4.2.6 on 2023-12-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_rating_user_alter_rating_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.BigIntegerField(null=True),
        ),
    ]
