# Generated by Django 4.2.6 on 2023-10-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("libraries", "0002_delete_library"),
    ]

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("branch", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=255)),
                ("postcode", models.CharField(max_length=10)),
                ("phone", models.CharField(max_length=20)),
                ("monday", models.CharField(blank=True, max_length=100, null=True)),
                ("tuesday", models.CharField(blank=True, max_length=100, null=True)),
                ("wednesday", models.CharField(blank=True, max_length=100, null=True)),
                ("thursday", models.CharField(blank=True, max_length=100, null=True)),
                ("friday", models.CharField(blank=True, max_length=100, null=True)),
                ("saturday", models.CharField(blank=True, max_length=100, null=True)),
                ("sunday", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("link", models.URLField(blank=True, max_length=1000, null=True)),
                ("NYU", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["-branch"],
            },
        ),
    ]
