# Generated by Django 4.2.6 on 2023-10-30 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("libraries", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="library",
            table="library",
        ),
    ]
