# Generated by Django 4.2.6 on 2023-11-06 00:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("libraries", "0005_alter_library_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="library",
            options={"managed": False, "ordering": ["branch"]},
        ),
    ]
