# Generated by Django 4.2.7 on 2023-11-02 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BookClub", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookclub",
            name="meetingSchedule",
        ),
        migrations.AddField(
            model_name="bookclub",
            name="meetingDay",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                    ("sunday", "Sunday"),
                ],
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bookclub",
            name="meetingEndTime",
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name="bookclub",
            name="meetingOccurence",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "One-Time"),
                    (2, "Weekly"),
                    (3, "Bi-weekly"),
                    (4, "Monthly"),
                ],
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bookclub",
            name="meetingStartTime",
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
    ]
