# Generated by Django 4.2.6 on 2023-11-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "BookClub",
            "0002_remove_bookclub_meetingschedule_bookclub_meetingday_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookclub",
            name="meetingOccurence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("one", "One-Time"),
                    ("weekly", "Weekly"),
                    ("bi-weekly", "Bi-weekly"),
                    ("monthly", "Monthly"),
                ],
                max_length=150,
                null=True,
            ),
        ),
    ]
