# Generated by Django 4.2.6 on 2023-11-19 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("BookClub", "0003_alter_bookclub_meetingoccurence"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookclub",
            name="silenceNotification",
            field=models.ManyToManyField(
                related_name="silence_notifications", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
