# Generated by Django 4.2.6 on 2023-12-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BookClub", "0004_bookclub_silencenotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("votes", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="bookclub",
            name="polls",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="VotingPoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poll_set", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=200)),
                ("choices", models.ManyToManyField(to="BookClub.pollchoice")),
            ],
        ),
    ]
