# Generated by Django 4.2.6 on 2023-12-05 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("BookClub", "0005_pollchoice_bookclub_polls_votingpoll"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollchoice",
            name="who_voted",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
