# Generated by Django 4.2.6 on 2023-12-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BookClub", "0008_pollchoice_user_voted"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookclub",
            name="currentAuthor",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="bookclub",
            name="currentBookIsbn",
            field=models.BigIntegerField(null=True),
        ),
    ]
