# Generated by Django 4.2.6 on 2023-11-25 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("BookClub", "0004_bookclub_silencenotification"),
        ("user", "0002_alter_customuser_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferOwnershipRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        max_length=30, verbose_name=["accepted", "pending", "declined"]
                    ),
                ),
                ("date_created", models.DateField(verbose_name="date created")),
                (
                    "book_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_club_in_limbo",
                        to="BookClub.bookclub",
                    ),
                ),
                (
                    "new_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="old_admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date_created"],
            },
        ),
    ]
