# Generated by Django 4.2.6 on 2023-12-05 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_transferownershiprequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TransferOwnershipRequest",
        ),
    ]
