# Generated by Django 4.2.6 on 2023-12-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Notifications", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="message",
        ),
        migrations.AddField(
            model_name="notification",
            name="safe_to_delete",
            field=models.BooleanField(default=False),
        ),
    ]
